export const languages = [
    { name: 'Afar',            value: 'aa', flag: 'country-dj'  },
    { name: 'Abkhazian',       value: 'ab', flag: 'country-ge'  },
    { name: 'Afrikaans',       value: 'af', flag: 'country-za'  },
    { name: 'Akan',            value: 'ak', flag: 'country-gh'  },
    { name: 'Amharic',         value: 'am', flag: 'country-et'  },
    { name: 'Arabic',          value: 'ar', flag: 'country-sa'  },
    { name: 'Assamese',        value: 'as', flag: 'country-in'  },
    { name: 'Awadhi',          value: 'aw', flag: 'country-in'  },
    { name: 'Aymara',          value: 'ay', flag: 'country-bo'  },
    { name: 'Azerbaijani',     value: 'az', flag: 'country-az'  },
    { name: 'Bhojpuri',        value: 'b1', flag: 'country-in'  },
    { name: 'Maithili',        value: 'b2', flag: 'country-np'  },
    { name: 'Bashkir',         value: 'ba', flag: 'country-ru'  },
    { name: 'Belarussian',     value: 'be', flag: 'country-by'  },
    { name: 'Bulgarian',       value: 'bg', flag: 'country-bg'  },
    { name: 'Bihari',          value: 'bh', flag: 'country-in'  },
    { name: 'Bislama',         value: 'bi', flag: 'country-vu'  },
    { name: 'Balochi',         value: 'bl', flag: 'country-pk'  },
    { name: 'Bengali',         value: 'bn', flag: 'country-bd'  },
    { name: 'Tibetan',         value: 'bo', flag: 'country-cn'  },
    { name: 'Breton',          value: 'br', flag: 'country-fr'  },
    { name: 'Catalan',         value: 'ca', flag: 'language-ca' }, // language without country flag
    { name: 'Cebuano',         value: 'cb', flag: 'country-ph'  },
    { name: 'Chechen',         value: 'ce', flag: 'language-ce' }, // language without country flag
    { name: 'Corsican',        value: 'co', flag: 'country-fr'  },
    { name: 'Czech',           value: 'cs', flag: 'country-cz'  },
    { name: 'Welsh',           value: 'cy', flag: 'language-cy' }, // language without country flag
    { name: 'Danish',          value: 'da', flag: 'country-dk'  },
    { name: 'German',          value: 'de', flag: 'country-de'  },
    { name: 'Dakhini',         value: 'dk', flag: 'country-in'  },
    { name: 'Bhutani',         value: 'dz', flag: 'country-bt'  },
    { name: 'Greek',           value: 'el', flag: 'country-gr'  },
    { name: 'English',         value: 'en', flag: 'country-gb'  },
    { name: 'Esperanto',       value: 'eo', flag: 'language-eo' }, // language without country flag
    { name: 'Spanish',         value: 'es', flag: 'country-es'  },
    { name: 'Estonian',        value: 'et', flag: 'country-ee'  },
    { name: 'Basque',          value: 'eu', flag: 'language-eu' }, // language without country flag
    { name: 'Persian',         value: 'fa', flag: 'country-ir'  },
    { name: 'Finnish',         value: 'fi', flag: 'country-fi'  },
    { name: 'Fiji',            value: 'fj', flag: 'country-fj'  },
    { name: 'Faeroese',        value: 'fo', flag: 'country-fo'  },
    { name: 'French',          value: 'fr', flag: 'country-fr'  },
    { name: 'Frisian',         value: 'fy', flag: 'country-nl'  },
    { name: 'Irish',           value: 'ga', flag: 'country-ie'  },
    { name: 'Scottish Gaelic', value: 'gd', flag: 'language-gd' }, // language without country flag
    { name: 'Galician',        value: 'gl', flag: 'language-gl' }, // language without country flag
    { name: 'Guarani',         value: 'gn', flag: 'country-py'  },
    { name: 'Gujarati',        value: 'gu', flag: 'country-in'  },
    { name: 'Hausa',           value: 'ha', flag: 'country-ne'  },
    { name: 'Hindi',           value: 'hi', flag: 'country-in'  },
    { name: 'Croatian',        value: 'hr', flag: 'country-hr'  },
    { name: 'Haitian Creole',  value: 'ht', flag: 'country-ht'  },
    { name: 'Hungarian',       value: 'hu', flag: 'country-hu'  },
    { name: 'Armenian',        value: 'hy', flag: 'country-am'  },
    { name: 'Interlingua',     value: 'ia', flag: 'language-ia' }, // language without country flag
    { name: 'Interlingue',     value: 'ie', flag: 'language-ie' }, // language without country flag
    { name: 'Inupiak',         value: 'ik', flag: 'language-ik' }, // language without country flag
    { name: 'Indonesian',      value: 'in', flag: 'country-id'  },
    { name: 'Icelandic',       value: 'is', flag: 'country-is'  },
    { name: 'Italian',         value: 'it', flag: 'country-it'  },
    { name: 'Hebrew',          value: 'iw', flag: 'country-il'  },
    { name: 'Japanese',        value: 'ja', flag: 'country-jp'  },
    { name: 'Yiddish',         value: 'ji', flag: 'language-ji' }, // language without country flag
    { name: 'Javanese',        value: 'jw', flag: 'country-id'  },
    { name: 'Georgian',        value: 'ka', flag: 'country-ge'  },
    { name: 'Kabyle',          value: 'kb', flag: 'country-dz'  },
    { name: 'Konkani',         value: 'ki', flag: 'country-in'  },
    { name: 'Kazakh',          value: 'kk', flag: 'country-kz'  },
    { name: 'Greenlandic',     value: 'kl', flag: 'country-gl'  },
    { name: 'Khmer',           value: 'km', flag: 'country-kh'  },
    { name: 'Kannada',         value: 'kn', flag: 'country-in'  },
    { name: 'Korean',          value: 'ko', flag: 'country-kr'  },
    { name: 'Kashmiri',        value: 'ks', flag: 'country-in'  },
    { name: 'Kurdish',         value: 'ku', flag: 'country-iq'  },
    { name: 'Kirghiz',         value: 'ky', flag: 'country-kg'  },
    { name: 'Latin',           value: 'la', flag: 'country-va'  },
    { name: 'Luxembourgish',   value: 'lb', flag: 'country-lu'  },
    { name: 'Lombard',         value: 'lm', flag: 'country-it'  },
    { name: 'Lingala',         value: 'ln', flag: 'country-cg'  },
    { name: 'Laothian',        value: 'lo', flag: 'country-la'  },
    { name: 'Lithuanian',      value: 'lt', flag: 'country-lt'  },
    { name: 'Latvian',         value: 'lv', flag: 'country-lv'  },
    { name: 'Malagasy',        value: 'mg', flag: 'country-mg'  },
    { name: 'Maori',           value: 'mi', flag: 'country-nz'  },
    { name: 'Macedonian',      value: 'mk', flag: 'country-mk'  },
    { name: 'Malayalam',       value: 'ml', flag: 'country-in'  },
    { name: 'Mongolian',       value: 'mn', flag: 'country-mn'  },
    { name: 'Moldavian',       value: 'mo', flag: 'country-md'  },
    { name: 'Marathi',         value: 'mr', flag: 'country-in'  },
    { name: 'Malay',           value: 'ms', flag: 'country-my'  },
    { name: 'Maltese',         value: 'mt', flag: 'country-mt'  },
    { name: 'Makhuwa',         value: 'mu', flag: 'country-mz'  },
    { name: 'Marwari',         value: 'mw', flag: 'country-in'  },
    { name: 'Burmese',         value: 'my', flag: 'country-mm'  },
    { name: 'Nauru',           value: 'na', flag: 'country-nr'  },
    { name: 'Nepali',          value: 'ne', flag: 'country-np'  },
    { name: 'Dutch',           value: 'nl', flag: 'country-nl'  },
    { name: 'Norwegian',       value: 'no', flag: 'country-no'  },
    { name: 'Occitan',         value: 'oc', flag: 'country-fr'  },
    { name: 'Oromo',           value: 'om', flag: 'country-et'  },
    { name: 'Oriya',           value: 'or', flag: 'country-in'  },
    { name: 'Punjabi',         value: 'pa', flag: 'country-pk'  },
    { name: 'Polish',          value: 'pl', flag: 'country-pl'  },
    { name: 'Pashto',          value: 'ps', flag: 'country-af'  },
    { name: 'Portuguese',      value: 'pt', flag: 'country-pt'  },
    { name: 'Quechua',         value: 'qu', flag: 'country-pe'  },
    { name: 'Rifian',          value: 'ri', flag: 'country-ma'  },
    { name: 'Rhaeto-Romance',  value: 'rm', flag: 'country-ch'  },
    { name: 'Kirundi',         value: 'rn', flag: 'country-bi'  },
    { name: 'Romanian',        value: 'ro', flag: 'country-ro'  },
    { name: 'Russian',         value: 'ru', flag: 'country-ru'  },
    { name: 'Kinyarwanda',     value: 'rw', flag: 'country-rw'  },
    { name: 'Sanskrit',        value: 'sa', flag: 'country-in'  },
    { name: 'Sindhi',          value: 'sd', flag: 'country-pk'  },
    { name: 'Sangro',          value: 'sg', flag: 'country-cf'  },
    { name: 'Serbo-Croatian',  value: 'sh', flag: 'country-rs'  },
    { name: 'Sinhalese',       value: 'si', flag: 'country-lk'  },
    { name: 'Slovak',          value: 'sk', flag: 'country-sk'  },
    { name: 'Slovenian',       value: 'sl', flag: 'country-si'  },
    { name: 'Samoan',          value: 'sm', flag: 'country-ws'  },
    { name: 'Shona',           value: 'sn', flag: 'country-zw'  },
    { name: 'Somali',          value: 'so', flag: 'country-so'  },
    { name: 'Albanian',        value: 'sq', flag: 'country-al'  },
    { name: 'Serbian',         value: 'sr', flag: 'country-rs'  },
    { name: 'Siswati',         value: 'ss', flag: 'country-sz'  },
    { name: 'Sesotho',         value: 'st', flag: 'country-ls'  },
    { name: 'Sundanese',       value: 'su', flag: 'country-id'  },
    { name: 'Swedish',         value: 'sv', flag: 'country-se'  },
    { name: 'Swahili',         value: 'sw', flag: 'country-ke'  },
    { name: 'Tamil',           value: 'ta', flag: 'country-lk'  },
    { name: 'Telugu',          value: 'te', flag: 'country-in'  },
    { name: 'Tajik',           value: 'tg', flag: 'country-tj'  },
    { name: 'Thai',            value: 'th', flag: 'country-th'  },
    { name: 'Tigrinya',        value: 'ti', flag: 'country-er'  },
    { name: 'Turkmen',         value: 'tk', flag: 'country-tm'  },
    { name: 'Tagalog',         value: 'tl', flag: 'country-ph'  },
    { name: 'Tuareg',          value: 'tm', flag: 'language-tm' }, // language without country flag
    { name: 'Setswana',        value: 'tn', flag: 'country-bw'  },
    { name: 'Tonga',           value: 'to', flag: 'country-to'  },
    { name: 'Turkish',         value: 'tr', flag: 'country-tr'  },
    { name: 'Tsonga',          value: 'ts', flag: 'country-za'  },
    { name: 'Tatar',           value: 'tt', flag: 'country-ru'  },
    { name: 'Twi',             value: 'tw', flag: 'country-gh'  },
    { name: 'Tamazight',       value: 'tz', flag: 'language-tz' }, // language without country flag
    { name: 'Uyghur',          value: 'ug', flag: 'country-cn'  },
    { name: 'Ukrainian',       value: 'uk', flag: 'country-ua'  },
    { name: 'Urdu',            value: 'ur', flag: 'country-pk'  },
    { name: 'Uzbek',           value: 'uz', flag: 'country-uz'  },
    { name: 'Vietnamese',      value: 'vi', flag: 'country-vn'  },
    { name: 'Volapuk',         value: 'vo', flag: 'language-vo' }, // language without country flag
    { name: 'Wolof',           value: 'wo', flag: 'country-sn'  },
    { name: 'Xhosa',           value: 'xh', flag: 'country-za'  },
    { name: 'Yoruba',          value: 'yo', flag: 'country-ng'  },
    { name: 'Chinese',         value: 'zh', flag: 'country-cn'  },
    { name: 'Zulu',            value: 'zu', flag: 'country-za'  }
];